In [2]:
import numpy as np

In [3]:
my_list=[1,2,3]

In [4]:
arr= np.array(my_list)

In [5]:
arr 

array([1, 2, 3])

In [6]:
my_mat=[[12,23,45],[34,34,434]]

In [7]:
np.array(my_mat)

array([[ 12,  23,  45],
       [ 34,  34, 434]])

In [8]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.linspace(0,5,500)

array([0.        , 0.01002004, 0.02004008, 0.03006012, 0.04008016,
       0.0501002 , 0.06012024, 0.07014028, 0.08016032, 0.09018036,
       0.1002004 , 0.11022044, 0.12024048, 0.13026052, 0.14028056,
       0.1503006 , 0.16032064, 0.17034068, 0.18036072, 0.19038076,
       0.2004008 , 0.21042084, 0.22044088, 0.23046092, 0.24048096,
       0.250501  , 0.26052104, 0.27054108, 0.28056112, 0.29058116,
       0.3006012 , 0.31062124, 0.32064128, 0.33066132, 0.34068136,
       0.3507014 , 0.36072144, 0.37074148, 0.38076152, 0.39078156,
       0.4008016 , 0.41082164, 0.42084168, 0.43086172, 0.44088176,
       0.4509018 , 0.46092184, 0.47094188, 0.48096192, 0.49098196,
       0.501002  , 0.51102204, 0.52104208, 0.53106212, 0.54108216,
       0.5511022 , 0.56112224, 0.57114228, 0.58116232, 0.59118236,
       0.6012024 , 0.61122244, 0.62124248, 0.63126253, 0.64128257,
       0.65130261, 0.66132265, 0.67134269, 0.68136273, 0.69138277,
       0.70140281, 0.71142285, 0.72144289, 0.73146293, 0.74148

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(4)

array([0.94205458, 0.37706033, 0.41651327, 0.7365192 ])

In [16]:
arr=np.arange(25)

In [17]:
np.random.randint(0,50,10)

array([ 6, 21, 19, 43, 24, 32,  8, 48, 14,  8])

In [18]:
arr.reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr.max()

24

In [20]:
arr.min()

0

In [21]:
arr = np.arange(0,11)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr[8]

8

In [24]:
arr[1:5]

array([1, 2, 3, 4])

In [25]:
arr[3:4]

array([3])

In [26]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [28]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
slice_of_arr=arr[0:6]

In [32]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [33]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [34]:
arr_copy=arr.copy()

In [35]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr_copy[:]=100

In [37]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr_2d = np.array([[5,10,15],[30,45,56],[45,67,78]])

In [40]:
arr_2d

array([[ 5, 10, 15],
       [30, 45, 56],
       [45, 67, 78]])

In [41]:
arr_2d[0][0]

5

In [42]:
arr_2d[0]

array([ 5, 10, 15])

In [43]:
arr_2d[1][1]

45

In [44]:
arr= np.arange(25)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
ranarr =np.random.randint(0,50,10)

In [47]:
ranarr

array([30,  8, 49, 31, 49, 11, 42,  3, 33,  4])

In [48]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
ranarr.max()

49

In [54]:
ranarr

array([30,  8, 49, 31, 49, 11, 42,  3, 33,  4])

In [55]:
ranarr.argmin()

7

In [56]:
ranarr.argmax()

2

In [58]:
arr.shape

(25,)

In [59]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr.shape

(25,)

In [61]:
arr.dtype

dtype('int32')